# Generated by Django 6.0.2 on 2026-03-02 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_trainingplan_trainingday'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingplan',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2026, 3, 2, 13, 45, 43, 768330, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2026, 3, 2, 13, 45, 50, 376372, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
